#!/usr/bin/env php
<?php
require(__DIR__."/SLGTerm/autoload.php");

use SLGTerm\Form;
use SLGTerm\Terminal;
use SLGTerm\Cursor;
use SLGTerm\Input;

return main();


function main() {

    Terminal::underline();

    echo "Manually resize terminal to test resize autodetection.\n";
    echo "Type '<ESC>' to quit.\n";

    Terminal::normal();

    $app = new Form();

    $app->on("key", function( $event ) {
        $key = $event->getData('key');
        if($key == "<ESC>") {
            $event->getData('controller')->hide();
            // setting exit to true will break the loop on next iteration
        }
    });

    Input::setInterval(function () use ($app) {
        static $cols;
        if (is_null($cols)) $cols = Terminal::cols();
        static $rows;
        if (is_null($rows)) $rows = Terminal::rows();

        if( $cols != Terminal::cols() || $rows != Terminal::rows()) {

            $oldDimensions = [ "cols" => $cols, "rows" => $rows ];
            $cols = Terminal::cols();
            $rows = Terminal::rows();
            $newDimensions = [ "cols" => $cols, "rows" => $rows ];

            $data = ["oldDimensions"=>$oldDimensions, "newDimensions"=>$newDimensions];

            echo "Resized! ".json_encode($data)."\n";
            $app->emit("resized", $data);

        }

    } , 1000); // query once per second



    $app->focus();

    return 0;
}
